# Generated by Django 4.2.6 on 2023-10-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dtm", models.DateTimeField()),
                ("ip", models.TextField()),
                ("user_agent", models.TextField()),
                ("accept_language", models.TextField()),
            ],
        ),
    ]
